### ISSUE TITLE
[vnext] Create APIs from Json

### ISSUE THREAD

**Issue by DeeJayTC** [DeeJayTC/net-dynamic-api#11]
In addition to the API from class I'd like to introduce an even more generic way supporting the use of docker and having a full "microservice". To do that I'm adding the option to create an API from a JSON defintion. 

JSON for an API will look something like this:

```json
[
  {
    "name": "Car",
    "route": "/cars",
    "caching": true,
    "cacheLiveTime": 1000,
    "events": "POST,PUT,DELETE",
    "Fields": [
      {
        "name": "Id",
        "type": "GUID"
      },
      {
        "name": "Name",
        "type": "String",
        "maxLength": "200",
        "nullable":  false 
      }
    ] 
  }
]
```

This JSON will auto generate a fully working CRUD API, ODATA enabled and database handling done automatically as well. All you have to do for a fully working API is to write a JSON schema.

**Comment by johntyrrell** [comment]
Cool,
Maybe you can add an option to use graphql instead of odata?
Will this generate the code that can be edited or should the generate code not be editable? If so, then maybe security filters would be handy

**Comment by DeeJayTC** [comment]
GraphQL is something i probably add at a later state. First of all OData to have a distinct difference to something like Hasura. For sure GraphQL is worth to add but not a priority. 

This will generate code at runtime, load the code and also generate the controllers at runtime. Everthing the lib does is happening at runtime. You can intercept things and add your own code but there's no must. 

The idea is basically, you add a json file to a docker container and the container just magically provides you everything out of the box automatically but allowing you to add your own code if you want to.

**Comment by DeeJayTC** [comment]
There's now a working sample here ->  https://github.com/DeeJayTC/net-dynamic-api/tree/11-api-from-json/sample/SampleAppJson

Have to clone, not on nuget yet
