### ISSUE TITLE
Postgres is not recognized as a database type

### ISSUE THREAD

**Issue by moalamri** [DeeJayTC/net-dynamic-api#32]
```log
Unhandled exception. 
System.InvalidOperationException: Failed to convert configuration value 
at 'Api:Database:DatabaseType' to type 'TCDev.APIGenerator.DbType'.
 ---> System.FormatException: Postgres is not a valid value for DbType.
 ---> System.ArgumentException: Requested value 'Postgres' was not found.
```
Could be because the enum of Postgres type is[ commented out here](https://github.com/DeeJayTC/net-dynamic-api/blob/010e424451ef2369e7aceaa55052240f83c70ef4/src/TCDev.APIGenerator.Schema/ApiGeneratorConfig.cs#L101)? Or is it not yet supported?

Thank you..

**Comment by DeeJayTC** [comment]
Ahh i think thats actually documented wrong or old. That Enum is a relic from ab older database version.

Try using https://www.nuget.org/packages/TCDev.APIGenerator.Data.Postgres/

And use AddDataContextSQL()

https://docs.rasepi.com/database-options

Have to update the docs here @moalamri and big sorry for the delay...vacation and stuff, forgot to check the issues!

**Comment by moalamri** [comment]
It's totally ok, thank you so much.
This is a huge time-saving tool 👍
I ended up using ServiceStack OrmLite & AutoQuery, which pretty much does the same except that it don't use EF.

I'll close this issue as you have cleared up the confusion 👍

Thank you
