### ISSUE TITLE
General Impressions.

### ISSUE THREAD

**Issue by crazedVic** [DeeJayTC/net-dynamic-api#38]
Just going to leave some feedback here.  So initially I followed this article [here](https://www.tcdev.de/crud-apis-in-an-instant) using visual studio 2022 (latest).  I created a new WebAPI project as instructed, using .Net 6.0.  I then ran the command as per the instructions `dotnet add package TCDev.ApiGenerator` and was told that `
Package 'TCDev.ApiGenerator' is incompatible with 'all' frameworks in project`.  So I deleted the solution.

So then I went to the instructions on the github page [here](url) where i followed the new instructions `dotnet add package TCDev.ApiGenerator --prerelease`  in a fresh project and this installed fine.  But pasting in the code right thereafter in the git didn't work either, as I'm guessing I was missing some dependencies.   I tried installing some but ran into even more errors, so I gave up and deleted the solution.

 So then my journey took me to yet another page[here](https://docs.rasepi.com/lets-get-started) where there were yet again new instructions, and subsequently i setup another fresh project.   And again the install steps failed unless i added the suffix --prerelease  and that sorta worked.  Tut then i went to add package TCDev.APIGenerator.Data.InMemory and was told it didn't exist or something like that.  Deleted project again.

Alright so at this point I have had zero luck, guessing my version of visual studio is too new.  So I clone the examples and open up simple-api in visual studio and run it (noticed that though the project is called simple-api the solution is called remote-api, not to be confused with the other remote-api example, though yet, still confusing).  After some reconfiguring of the db connection string, i thought I was off to the races.  But no, apparently there's an issue with the Schedule List in courses: 
```
The entity type 'List<DateTime>' requires a primary key to be defined. If you intended to use a keyless entity type, call 'HasNoKey' in 'OnModelCreating'.
```
So i commented out that line and finally got something working.  But it shouldn't be that much of a challenge, as it defeats the whole purpose of your solution which is to provide  a fast and easy way to get an API up and running.

**Comment by DeeJayTC** [comment]
Hey!
Sorry to hear that, some of the documentation is indeed a bit outdated sadly. 
I'm using this a lot myself but forgot to update a few pieces. 

Still surprised about a few things you mentioned. 

>  Package 'TCDev.ApiGenerator' is incompatible with 'all' frameworks in project

Can you tell me the version you've been running there? Ie the template? was that WebAPI for .NET 6 exactly?

Also what do you mean by:

> But pasting in the code right thereafter in the git
